
# SEO settings
title: "拼命奔跑的大蜗牛"
title2: "" # default: ""
description: "昨夜星辰昨夜风"
keywords: "machine learning,cv,nlp,c++,algorithm"
url: https://github.com/zhouyelihua # site url
baseurl: "/zhouyelihua.github.io" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

repo: https://github.com/zhouyelihua/zhouyelihua.github.io
disqus_shortname: "snail"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "a running-snail"
  job      : "R&D Software Engineer..."
  bio      : "冰冷的机器将改变冰冷的世界...."
  thumb    : /images/author.jpg
  email    : yeahpingye@gmail.com
  url      : https://github.com/zhouyelihua/zhouyelihua.github.io
  github   : https://github.com/zhouyelihua/zhouyelihua.github.io

# social settings
og_locale: "en_US"
twitter_card: ""
twitter_site: "@"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
